### ISSUE TITLE
Match CRC from C code to crc-full

### ISSUE THREAD

**Issue by galvesribeiro** [RioloGiuseppe/crc-full#1]
Hello,

I have to send a message from typescript to our device and at the device side, it validates the message using a CRC16.

Here is how the device validates it:

```c
#define CRC_MASK 0x1021 /* x^16 + x^12 + x^5 + x^0 */

UINT16 CRC_Calc (unsigned char *pbData, int iLength)
{
    UINT16 wData, wCRC = 0;
    int i;

    for ( ;iLength > 0; iLength--, pbData++) {
        wData = (UINT16) (((UINT16) *pbData) << 8);
        for (i = 0; i < 8; i++, wData <<= 1) {
            if ((wCRC ^ wData) & 0x8000)
                wCRC = (UINT16) ((wCRC << 1) ^ CRC_MASK);
            else
                wCRC <<= 1;
        }
    }
    return wCRC;
}
```

The input data would be `"OPN\x17"` (where `\x17` is an `ETB` control character). The output must be `A8A9`.

Given that input data, the C sample code, can you provide me a sample code using your package to achieve the same result?

Thank you! I appreciate any help.

Best regards,
Gutemberg

**Comment by RioloGiuseppe** [comment]
Hello,
I just made some tries. I think you get a wrong result because you are passing `"OPN\x17"` as string. If you pass the equivalent byte array of ascii characters, you will havethe same result of C/C++.

As in the readme:
```ts
import {CRC} from 'crc-full'
var crc = new CRC(16, "CRC16", 0x1021, 0x0000, 0x0000, false, false);
var res = crc .compute([0x4F, 0x50, 0x4E, 0x17]);        // Array with ascii integer of "OPN\x17"
```
The result (number) is `43177` but if you convert to an hex string you will have: `'a8a9'`, that is the same result obtained in C.

```ts
h_string = res.toString(16)
```

Hope to been useful
Best regards
Giuseppe Riolo

**Comment by galvesribeiro** [comment]
@RioloGiuseppe hello! Thank you very much for the quick response.

> If you pass the equivalent byte array of ascii characters

How did you got the ascii chars from `OPN` string?

Thanks!

**Comment by galvesribeiro** [comment]
@RioloGiuseppe hello! Thank you very much for the quick response.

I got it working!

If I may, I'm whiling to contribute an update to your repo and package so it can be easily consumed from npm. Right now, you are asking people to install typescript, which shouldn't be required since they may want to use it on JS as well.

If you accept the PR and will update the npm package, I can push it later Today.

Thanks!

**Comment by RioloGiuseppe** [comment]
You're welcome!
Yes. To do it fast I used [this online tool](http://onlinecalculators.brainmeasures.com/Conversions/StringtoAsciiCalculator.aspx), so `OPN` became `0x4F, 0x50, 0x4E` and `\x17` is an escaped form of `0x17` (I don 't know in which convention).

> If I may, I'm whiling to contribute an update to your repo and package so it can be easily consumed from npm. Right now, you are asking people to install typescript, which shouldn't be required since they may want to use it on JS as well.

Yes, you are right, including the compiled javascript tsc will not a dependency any more. You can make a PR when you want.


Best regards!
